# Generated by Django 3.1 on 2022-02-16 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='estado_perfil',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estado',
                'ordering': ['estado'],
            },
        ),
        migrations.CreateModel(
            name='perfiles_ocupacionales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('universidad', models.CharField(max_length=100, verbose_name='Universidad')),
                ('programa', models.CharField(max_length=100, verbose_name='Programa')),
                ('perfil', models.CharField(max_length=100, verbose_name='Perfil Ocupacional')),
                ('fecha_creacion', models.DateField(auto_now=True, verbose_name='Fecha de creacion')),
                ('estado_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Perfiles.estado_perfil', verbose_name='Estado')),
            ],
        ),
    ]
