# Generated by Django 3.1 on 2022-04-24 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='historico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('busqueda', models.TextField(verbose_name='Busqueda')),
                ('perfiles', models.CharField(max_length=200, verbose_name='Perfiles')),
                ('fecha_creacion', models.DateField(auto_now=True, verbose_name='Fecha de creacion')),
            ],
        ),
        migrations.AlterField(
            model_name='perfiles_ocupacionales',
            name='perfil',
            field=models.TextField(verbose_name='Perfil Ocupacional'),
        ),
    ]
