# Generated by Django 3.1 on 2022-02-25 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfiles_ocupacionales',
            name='perfil',
            field=models.TextField(verbose_name='Perfil Ocupacional'),
        ),
    ]
