# Generated by Django 3.1 on 2022-04-04 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfiles', '0002_auto_20220224_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='tmp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('string', models.TextField(verbose_name='String')),
                ('tipo', models.IntegerField(verbose_name='Tipo')),
                ('referenciaid', models.IntegerField(verbose_name='Referencia')),
            ],
        ),
    ]
