# Generated by Django 3.1 on 2022-04-04 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfiles', '0003_tmp'),
    ]

    operations = [
        migrations.CreateModel(
            name='referencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('referencia', models.CharField(max_length=100, verbose_name='Referencia')),
            ],
        ),
        migrations.CreateModel(
            name='tipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo')),
            ],
        ),
    ]
